=== geoblacklight/geoblacklight/schema/geoblacklight-schema-aardvark.json
{
  "$schema": "http://json-schema.org/schema#",
  "description": "Schema for GeoBlacklight. See https://opengeometadata.github.io/aardvark/aardvarkMetadata.html for more details.",
  "id": "http://geoblacklight.org/schema/aardvark",
  "title": "GeoBlacklight Schema - Aardvark",
  "type": "object",
  "properties": {
    "dct_title_s": { "type": "string" },
    "dct_alternative_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_description_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_language_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "gbl_displayNote_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_creator_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_publisher_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "schema_provider_s": { "type": "string" },
    "gbl_resourceClass_sm": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["Datasets", "Maps", "Imagery", "Collections", "Websites", "Web services", "Other"]
      }
    },
    "gbl_resourceType_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_subject_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dcat_theme_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dcat_keyword_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_temporal_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_issued_s": { "type": "string" },
    "gbl_indexYear_im": {
      "type": "array",
      "items": {
        "type": "integer"
      }
    },
    "gbl_dateRange_drsim": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_spatial_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "locn_geometry": { "type": "string" },
    "dcat_bbox": { "type": "string" },
    "dcat_centroid": { "type": "string" },
    "dct_relation_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "pcdm_memberOf_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_isPartOf_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_source_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_isVersionOf_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_replaces_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_isReplacedBy_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_rights_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_rightsHolder_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_license_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_accessRights_s": { "type": "string" },
    "dct_format_s": { "type": "string" },
    "gbl_fileSize_s": { "type": "string" },
    "gbl_wxsIdentifier_s": { "type": "string" },
    "dct_references_s": { "type": "string" },
    "id": { "type": "string" },
    "dct_identifier_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "gbl_mdModified_dt": {
      "type": "string",
      "format": "date-time"
    },
    "gbl_mdVersion_s": {
      "type": "string",
      "const": "Aardvark"
    },
    "gbl_suppressed_b": { "type": ["string", "boolean"] },
    "gbl_georeferenced_b": { "type": ["string", "boolean"] }
  },
  "required": ["id", "dct_title_s", "gbl_resourceClass_sm", "dct_accessRights_s", "gbl_mdVersion_s"]
}

=== geoblacklight/geoblacklight/spec/fixtures/solr_documents/princeton-child2.json
{
  "dct_title_s": "Princeton, Mercer County, New Jersey (Sheet 2)",
  "dct_alternative_sm": ["princeton-child2"],
  "dct_description_sm": [
    "Child record for testing the gbl_suppressed_b property. ",
    "Title taken from sheet 1 of 1927 map. \"Feb. 1885.\" Includes location map and key. Oriented with the north to the upper left."
  ],
  "dct_language_sm": ["eng"],
  "dct_creator_sm": ["Sanborn Map Company"],
  "dct_publisher_sm": ["New York : Sanborn Map & Publishing Co., Limited, 1885."],
  "schema_provider_s": "Princeton",
  "gbl_resourceClass_sm": ["Maps"],
  "dct_subject_sm": ["Real property-New Jersey-Princeton-Maps", "Princeton (N.J.)-Maps"],
  "dcat_keyword_sm": ["GBL Fixture records"],
  "locn_geometry": "ENVELOPE(-74.68,-74.63,40.37,40.33)",
  "dcat_bbox": "ENVELOPE(-74.68,-74.63,40.37,40.33)",
  "dcat_centroid": "40.349999999999994,-74.655",
  "dct_source_sm": ["princeton-1r66j405w"],
  "dct_accessRights_s": "Public",
  "dct_format_s": "TIFF",
  "gbl_wxsIdentifier_s": "public-figgy:p-db890be9-02bf-43c1-85c8-69c0684e25f6",
  "dct_references_s": "{\"http://schema.org/downloadUrl\":\"https://figgy.princeton.edu/downloads/db890be9-02bf-43c1-85c8-69c0684e25f6/file/dc08e083-5044-4949-bdd1-9d16a1fef818\",\"http://iiif.io/api/image\":\"https://libimages1.princeton.edu/loris/figgy_prod/a6%2Fb9%2Ff9%2Fa6b9f96251724546ae37ea3fa37a5e57%2Fintermediate_file.jp2/info.json\",\"http://schema.org/url\":\"https://catalog.princeton.edu/catalog/4266648\",\"http://iiif.io/api/presentation#manifest\":\"https://figgy.princeton.edu/concern/scanned_maps/68e90289-74ce-4f21-89e5-852f3e96ce35/manifest\"}",
  "id": "princeton-jq085m62x",
  "dct_identifier_sm": ["ark:/88435/jq085m62x", "HMC04 (Princeton)"],
  "gbl_mdModified_dt": "2021-06-01T22:14:16Z",
  "gbl_mdVersion_s": "Aardvark",
  "gbl_suppressed_b": true
}

=== geoblacklight/geoblacklight/spec/fixtures/solr_documents/complex-geom.json
{
  "id": "c8b46b52-0846-4abb-ba56-b484064f84ac",
  "gbl_mdVersion_s": "Aardvark",
  "dct_title_s": "Anglesey; Garnesay; Wight olim vectis; Iarsay; Per Gerardum Mercatorem.; Title on verso: Isles d'Anglesey Wight Jarsay et Garnesay",
  "dct_description_sm": [
    "Relief shown pictorially. Each map is 15 x 21 cm. Does not match any states listed in Van der Krogt. From the Appendix Atlas of the British Isles and Northern Europe, title created to represent a unique collection within the Clark Library, University of Michigan. 4 maps on one sheet: 30 x 43 cm."
  ],
  "dct_language_sm": ["eng"],
  "dct_creator_sm": [
    "Hondius, Hendrik, 1597-1651. Appendix Atlas of the British Isles and Northern Europe",
    "Jansson, Jan, 1588-1664. Appendix Atlas of the British Isles and Northern Europe",
    "Mercator, Gerhard, 1512-1594",
    "Vignaud, Henry, 1830-1922, former owner."
  ],
  "schema_provider_s": "University of Michigan",
  "gbl_resourceClass_sm": ["Maps"],
  "dcat_keyword_sm": ["Clark Library Map Collections", "2022-creator-sprint"],
  "dct_temporal_sm": ["between 1630 and 1639"],
  "gbl_indexYear_im": [1630],
  "gbl_dateRange_drsim": ["[1630 TO 1639]"],
  "dct_spatial_sm": ["Isle of Wight", "Guernsey (Isle)", "Jersey (Isle)", "Anglesey (Isle)", "England", "Wales"],
  "locn_geometry": "MULTIPOLYGON(((-4.7 53.44, -4.02 53.44, -4.02 53.13, -4.7 53.13, -4.7 53.44)),((-1.591789 50.767556, -1.062732 50.767556, -1.062732 50.574678, -1.591789 50.574678, -1.591789 50.767556)),((-2.6825 49.5351, -2.3117 49.5351, -2.3117 49.3851, -2.6825 49.3851, -2.6825 49.5351)),((-2.2649 49.2775, -1.9958 49.2775, -1.9958 49.1411, -2.2649 49.1411, -2.2649 49.2775)),((-5.1707 54.5534, -3.9654 54.5534, -3.9654 53.845, -5.1707 53.845, -5.1707 54.5534)))",
  "dcat_bbox": "ENVELOPE(-4.98,-1.04,54.47,49.14)",
  "dcat_centroid": "51.805,-3.0100000000000002",
  "pcdm_memberOf_sm": ["64bd8c4c-8e60-4956-b43d-bdc3f93db488"],
  "dct_isPartOf_sm": ["07d-01"],
  "dct_rights_sm": ["This map is in the public domain."],
  "dct_rightsHolder_sm": [
    "Please attribute access and use of this digitized map to the Stephen S. Clark Library, University of Michigan Library. https://www.lib.umich.edu/about-us/policies/copyright-policy"
  ],
  "dct_accessRights_s": "Public",
  "dct_format_s": "JPEG",
  "dct_references_s": "{\"http://schema.org/url\":\"https://quod.lib.umich.edu/c/clark1ic/x-010356232/39015091191992_01\",\"http://iiif.io/api/presentation#manifest\":\"https://quod.lib.umich.edu/cgi/i/image/api/search/clark1ic:010356232\"}",
  "dct_identifier_sm": ["c8b46b52-0846-4abb-ba56-b484064f84ac"]
}

=== geoblacklight/geoblacklight/spec/fixtures/solr_documents/iiif-eastern-hemisphere.json
{
  "dct_title_s": "A new & accurate map of Asia: drawn from actual surveys, and otherwise collected from journals; assisted by the most approved modern maps & charts. the whole being regulated by astron. observations",
  "dct_alternative_sm": ["iiif-eastern-hemisphere"],
  "dct_description_sm": [
    "Eastern hemisphere scanned map with IIIF manifest. ",
    "Cartographic Details: Scale [1:26,000,000]. Numbered \"N⁰52.\" Decorative title cartouche with palm tree. Shows boundaries, rivers, islands and principal settlements. Relief shown pictorially. London meridian. 35 x 43 cm"
  ],
  "dct_language_sm": ["eng"],
  "dct_creator_sm": ["Bowen, Emanuel (-1767)"],
  "schema_provider_s": "University of Minnesota",
  "gbl_resourceClass_sm": ["Maps"],
  "dcat_keyword_sm": ["GBL Fixture records"],
  "dct_temporal_sm": ["1750"],
  "gbl_indexYear_im": [1750],
  "gbl_dateRange_drsim": ["[1750 TO 1750]"],
  "locn_geometry": "MULTIPOLYGON (((-180 81.66,-168.35 81.66,-168.35 -12.93, -180 -12.93, -180 81.66),(25 81.66,25 -12.93,180 -12.93,180 81.66, 25 81.66)))",
  "dcat_bbox": "ENVELOPE(25,-168.35,81.66,-12.93)",
  "dcat_centroid": "34.365,-71.675",
  "dct_accessRights_s": "Public",
  "dct_format_s": "JPEG",
  "dct_references_s": "{\"http://schema.org/downloadUrl\":\"https://umedia.lib.umn.edu/sites/default/files/archive/113/image/tiff/1058396.tif\",\"http://schema.org/url\":\"http://purl.umn.edu/200804\",\"http://iiif.io/api/presentation#manifest\":\"https://cdm16022.contentdm.oclc.org/iiif/info/p16022coll246/224/manifest.json\"}",
  "id": "57f0f116-b64e-4773-8684-96ba09afb549",
  "dct_identifier_sm": ["57f0f116-b64e-4773-8684-96ba09afb549"],
  "gbl_mdModified_dt": "2021-06-01T22:14:16Z",
  "gbl_mdVersion_s": "Aardvark"
}

=== geoblacklight/geoblacklight/spec/fixtures/solr_documents/uva_slug_colon.json
{
  "dct_title_s": "Norfolk 2005 Police Stations",
  "dct_alternative_sm": ["uva_slug_colon"],
  "dct_description_sm": [
    "Multipoint dataset with WMS and WFS and a colon in the slug and layer ID. ",
    "Police stations for Norfolk, Virginia."
  ],
  "dct_language_sm": ["eng"],
  "schema_provider_s": "UVa",
  "gbl_resourceClass_sm": ["Datasets"],
  "gbl_resourceType_sm": ["Multipoint data"],
  "dcat_theme_sm": ["Location"],
  "dcat_keyword_sm": ["GBL Fixture records"],
  "dct_temporal_sm": ["2015-2018"],
  "dct_issued_s": "2008-10-17",
  "gbl_indexYear_im": [2015],
  "gbl_dateRange_drsim": ["[2015 TO 2018]"],
  "locn_geometry": "ENVELOPE(-76.346,-76.176,36.971,36.82)",
  "dcat_bbox": "ENVELOPE(-76.346,-76.176,36.971,36.82)",
  "dcat_centroid": "36.8955,-76.261",
  "dct_accessRights_s": "Public",
  "dct_format_s": "Shapefile",
  "gbl_wxsIdentifier_s": "Norfolk:police_point",
  "dct_references_s": "{\"http://schema.org/downloadUrl\":\"https://gis.lib.virginia.edu/geoserver/ows?service=WFS\\\\u0026typeName=Norfolk:police_point\\\\u0026request=GetFeature\\\\u0026outputFormat=shape-zip\",\"http://www.isotc211.org/schemas/2005/gmd/\":\"https://opengeometadata.github.io/edu.virginia/382/13/iso19139.xml\",\"http://www.opengis.net/def/serviceType/ogc/wfs\":\"http://gis.lib.virginia.edu/geoserver/wfs\",\"http://www.opengis.net/def/serviceType/ogc/wms\":\"http://www.opengis.net/def/serviceType/ogc/wms:http://gis.lib.virginia.edu/geoserver/wms\"}",
  "id": "uva-Norfolk:police_point",
  "dct_identifier_sm": ["315fc8ee-3b57-4ebb-aa24-4300f1c42dc9-13"],
  "gbl_mdModified_dt": "2021-06-01T22:14:17Z",
  "gbl_mdVersion_s": "Aardvark"
}

=== geoblacklight/geoblacklight/spec/fixtures/solr_documents/display-note.json
{
  "dct_title_s": "Building Footprints, Frobozz Headquarters, 781 GUE",
  "dct_description_sm": ["This is just a test record that has a couple of display notes."],
  "dct_language_sm": ["eng"],
  "gbl_displayNote_sm": [
    "This is a generic note about the resource that may be useful to users of this data.",
    "Danger: This document is highly flammable.",
    "Info: This dataset represents the buildings before they were destroyed by the Curse of Megaboz.",
    "Tip: Be sure to look in the mailbox outside the white house.",
    "Warning: This data is fictional."
  ],
  "dct_creator_sm": ["FrobozzCo International"],
  "dct_publisher_sm": ["FrobozzCo International"],
  "schema_provider_s": "Cornell",
  "gbl_resourceClass_sm": ["Datasets"],
  "gbl_resourceType_sm": ["Polygon data"],
  "dct_subject_sm": ["Buildings"],
  "dcat_keyword_sm": ["GBL Fixture records"],
  "dct_temporal_sm": ["781 GUE"],
  "dct_issued_s": "1983-01-01",
  "gbl_indexYear_im": [1983],
  "dct_spatial_sm": ["Flatheadia, Great Underground Empire"],
  "locn_geometry": "ENVELOPE(-71.118450,-71.074848,42.381246,42.354612)",
  "dcat_bbox": "ENVELOPE(-71.118450,-71.074848,42.381246,42.354612)",
  "dct_accessRights_s": "Public",
  "dct_format_s": "Shapefile",
  "id": "frobozz-111",
  "gbl_mdModified_dt": "2023-03-03T18:29:16Z",
  "gbl_mdVersion_s": "Aardvark"
}

=== geoblacklight/geoblacklight/spec/fixtures/solr_documents/xyz.json
{
  "dct_identifier_sm": ["6f47b103-9955-4bbe-a364-387039623106"],
  "dct_title_s": "Quaternary Fault and Fold Database of the United States (XYZ)",
  "dct_description_sm": ["Quaternary Fault and Fold Database of the United States"],
  "dct_accessRights_s": "Public",
  "schema_provider_s": "Stanford",
  "dct_references_s": "{\"http://schema.org/url\":\"https://www.usgs.gov/natural-hazards/earthquake-hazards/faults\",\"https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames\":\"https://earthquake.usgs.gov/basemap/tiles/faults/{z}/{x}/{y}.png\",\"http://schema.org/downloadUrl\":\"https://earthquake.usgs.gov/static/lfs/nshm/qfaults/Qfaults_GIS.zip\"}",
  "id": "6f47b103-9955-4bbe-a364-387039623106-xyz",
  "gbl_resourceClass_sm": ["Datasets", "Web services"],
  "gbl_resourceType_sm": ["Line data"],
  "dct_format_s": "Shapefile",
  "dct_language_sm": ["eng"],
  "dct_publisher_sm": ["Geological Survey (U.S.)"],
  "dct_subject_sm": ["Earthquakes", "Faults"],
  "dct_issued_s": "2020",
  "gbl_indexYear_im": [2020],
  "dct_temporal_sm": ["2020"],
  "dct_spatial_sm": ["Earth (Planet)", "North America"],
  "locn_geometry": "ENVELOPE(-156.02, -70.80, 65.59, 18.93)",
  "dcat_bbox": "ENVELOPE(-156.02, -70.80, 65.59, 18.93)",
  "gbl_mdModified_dt": "2021-06-11T17:55:01Z",
  "gbl_mdVersion_s": "Aardvark"
}

=== geoblacklight/geoblacklight/spec/fixtures/solr_documents/princeton-parent.json
{
  "dct_title_s": "Princeton, Mercer County, New Jersey",
  "dct_alternative_sm": ["princeton-parent"],
  "dct_description_sm": [
    "Parent record for testing the gbl_suppressed_b property. ",
    "Title taken from sheet 1 of 1927 map. \"Feb. 1885.\" Includes location map and key. Oriented with the north to the upper left."
  ],
  "dct_language_sm": ["eng"],
  "dct_creator_sm": ["Sanborn Map Company"],
  "dct_publisher_sm": ["New York : Sanborn Map & Publishing Co., Limited, 1885.", "Princeton University Library"],
  "schema_provider_s": "Princeton",
  "gbl_resourceClass_sm": ["Maps"],
  "dct_subject_sm": ["Real property-New Jersey-Princeton-Maps", "Princeton (N.J.)-Maps"],
  "dcat_keyword_sm": ["GBL Fixture records"],
  "gbl_indexYear_im": [1885],
  "gbl_dateRange_drsim": ["[1885 TO 1885]"],
  "locn_geometry": "ENVELOPE(-74.68,-74.63,40.37,40.33)",
  "dcat_bbox": "ENVELOPE(-74.68,-74.63,40.37,40.33)",
  "dcat_centroid": "40.350,-74.655",
  "dct_accessRights_s": "Public",
  "gbl_wxsIdentifier_s": "ark:/88435/1r66j405w",
  "dct_references_s": "{\"http://iiif.io/api/image\":\"https://libimages1.princeton.edu/loris/figgy_prod/5a%2F20%2F58%2F5a20585db50d44959fe5ae44821fd174%2Fintermediate_file.jp2/info.json\",\"http://schema.org/url\":\"https://catalog.princeton.edu/catalog/4266648\",\"http://iiif.io/api/presentation#manifest\":\"https://figgy.princeton.edu/concern/scanned_maps/9a193476-5f2e-4f82-95a5-6db472e39b7b/manifest\"}",
  "id": "princeton-1r66j405w",
  "dct_identifier_sm": ["ark:/88435/1r66j405w", "HMC04 (Princeton)"],
  "gbl_mdModified_dt": "2021-06-11T17:55:01Z",
  "gbl_mdVersion_s": "Aardvark"
}

=== geoblacklight/geoblacklight/spec/fixtures/solr_documents/b1g_wabash_parent.json
{
  "dct_title_s": "Wabash County Aerial Photography: Illinois, 1938",
  "dct_description_sm": [
    "See Related Records below to download individual sheets as GeoTIFFs. Statewide aerial photographs were first acquired for Illinois from 1937 through 1947. The original silver nitrate film negatives were destroyed in the early 1980s due to deterioration, so the photographic paper prints scanned for this collection are now the best substitute for them. This record covers Wabash County, photographed in 1938."
  ],
  "dct_language_sm": ["eng"],
  "schema_provider_s": "University of Illinois Urbana-Champaign",
  "dct_publisher_sm": ["Illinois State Geological Survey"],
  "gbl_resourceClass_sm": ["Imagery"],
  "dcat_theme_sm": ["Imagery"],
  "dcat_keyword_sm": ["Aerial photographs", "Historical imagery"],
  "dct_temporal_sm": ["1938"],
  "gbl_indexYear_im": [1938],
  "gbl_dateRange_drsim": ["[1938 TO 1938]"],
  "dct_spatial_sm": ["Illinois", "Wabash County, Illinois"],
  "locn_geometry": "ENVELOPE(-88.0094,-87.6113,38.6078,38.2158)",
  "dcat_bbox": "ENVELOPE(-88.0094,-87.6113,38.6078,38.2158)",
  "dcat_centroid": "38.4118,-87.81035",
  "pcdm_memberOf_sm": ["dc8c18df-7d64-4ff4-a754-d18d0891187d"],
  "dct_isPartOf_sm": ["09d-01"],
  "dct_accessRights_s": "Public",
  "dct_format_s": "Image Service",
  "dct_references_s": "{\"urn:x-esri:serviceType:ArcGIS#ImageMapLayer\":\"https://data.isgs.illinois.edu/arcgis/rest/services/Imagery/IL_Wabash_1938/ImageServer\",\"http://schema.org/url\":\"https://clearinghouse.isgs.illinois.edu/data/imagery/1937-1947-illinois-historical-aerial-photography\"}",
  "id": "eee6150b-ce2f-4837-9d17-ce72a0c1c26f",
  "dct_identifier_sm": ["eee6150b-ce2f-4837-9d17-ce72a0c1c26f"],
  "gbl_mdModified_dt": "2026-08-31T00:00:00Z",
  "gbl_mdVersion_s": "Aardvark"
}
