=== geoblacklight/geoblacklight/schema/geoblacklight-schema-aardvark.json
{
  "$schema": "http://json-schema.org/schema#",
  "description": "Schema for GeoBlacklight. See https://opengeometadata.github.io/aardvark/aardvarkMetadata.html for more details.",
  "id": "http://geoblacklight.org/schema/aardvark",
  "title": "GeoBlacklight Schema - Aardvark",
  "type": "object",
  "properties": {
    "dct_title_s": { "type": "string" },
    "dct_alternative_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_description_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_language_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "gbl_displayNote_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_creator_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_publisher_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "schema_provider_s": { "type": "string" },
    "gbl_resourceClass_sm": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["Datasets", "Maps", "Imagery", "Collections", "Websites", "Web services", "Other"]
      }
    },
    "gbl_resourceType_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_subject_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dcat_theme_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dcat_keyword_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_temporal_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_issued_s": { "type": "string" },
    "gbl_indexYear_im": {
      "type": "array",
      "items": {
        "type": "integer"
      }
    },
    "gbl_dateRange_drsim": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_spatial_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "locn_geometry": { "type": "string" },
    "dcat_bbox": { "type": "string" },
    "dcat_centroid": { "type": "string" },
    "dct_relation_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "pcdm_memberOf_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_isPartOf_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_source_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_isVersionOf_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_replaces_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_isReplacedBy_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_rights_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_rightsHolder_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_license_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dct_accessRights_s": { "type": "string" },
    "dct_format_s": { "type": "string" },
    "gbl_fileSize_s": { "type": "string" },
    "gbl_wxsIdentifier_s": { "type": "string" },
    "dct_references_s": { "type": "string" },
    "id": { "type": "string" },
    "dct_identifier_sm": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "gbl_mdModified_dt": {
      "type": "string",
      "format": "date-time"
    },
    "gbl_mdVersion_s": {
      "type": "string",
      "const": "Aardvark"
    },
    "gbl_suppressed_b": { "type": ["string", "boolean"] },
    "gbl_georeferenced_b": { "type": ["string", "boolean"] }
  },
  "required": ["id", "dct_title_s", "gbl_resourceClass_sm", "dct_accessRights_s", "gbl_mdVersion_s"]
}

=== geoblacklight/geoblacklight/spec/fixtures/solr_documents/restricted-line.json
{
  "dct_creator_sm": [
    "East View Geospatial"
  ],
  "dct_description_sm": [
    "This line dataset shows the road network in Port-au-Prince, Haiti, consisting of primary roads, secondary roads, and narrow local roads, tracks and trails, and lists the names of some roads. It was created in 2010 after the earthquake. The data was mapped at a scale of 1:12,500."
  ],
  "dct_format_s": "Shapefile",
  "dct_identifier_sm": [
    "https://spatial.lib.berkeley.edu/viewpublic/berkeley-s76d73"
  ],
  "dct_publisher_sm": [
    "East View Geospatial"
  ],
  "dct_accessRights_s": "Restricted",
  "dct_subject_sm": [
    "Transportation",
    "Roads",
    "Streets"
  ],
  "dct_title_s": "Roads, Port-au-Prince, Haiti, 2010",
  "dct_issued_s": "2010-04-01",
  "schema_provider_s": "University of California Berkeley",
  "dct_references_s": "{\"http://www.opengis.net/def/serviceType/ogc/wfs\":\"https://geoservices-secure.lib.berkeley.edu/geoserver/wfs\",\"http://www.opengis.net/def/serviceType/ogc/wms\":\"https://geoservices-secure.lib.berkeley.edu/geoserver/wms\",\"http://www.isotc211.org/schemas/2005/gmd/\":\"https://spatial.lib.berkeley.edu/metadata/berkeley-s76d73/iso19139.xml\",\"http://schema.org/downloadUrl\":\"https://spatial.lib.berkeley.edu/UCB/berkeley-s76d73/data.zip\"}",
  "dct_spatial_sm": [
    "Port-au-prince (Haiti)"
  ],
  "gbl_resourceType_sm": [
    "Line data",
    "Vector data"
  ],
  "gbl_wxsIdentifier_s": "s76d73",
  "gbl_mdModified_dt": "2019-01-10T23:34:35.206Z",
  "id": "berkeley-s76d73",
  "locn_geometry": "ENVELOPE(-72.429028, -72.190757, 18.667664, 18.420145)",
  "dcat_bbox": "ENVELOPE(-72.429028, -72.190757, 18.667664, 18.420145)",
  "gbl_indexYear_im": [
    2010
  ],
  "gbl_mdVersion_s": "Aardvark",
  "gbl_resourceClass_sm": [
    "Datasets"
  ]
}

=== geoblacklight/geoblacklight/spec/fixtures/solr_documents/baruch_ancestor2.json
{
  "dct_title_s": "2016 NYC Geodatabase, ArcGIS Version (jan2016)",
  "dct_alternative_sm": ["baruch_ancestor2"],
  "dct_description_sm": [
    "Geodatabase with documentation download. Referenced as parent. ",
    "The NYC Geodatabase (nyc_gdb) is a resource designed for basic geographic analysis and thematic mapping within the five boroughs of New York City. It contains geographic features and data compiled from several public sources. Subsets of large features like water, greenspace, and public facilities were created and Census geographies like tracts, ZCTAs, and PUMAs were geoprocessed to create land-based boundaries. Census data from the 2010 Census, American Community Survey (ACS), and ZIP Code Business Patterns are stored in tables that can be easily related to geographic features. Transit and public facility point data were gathered from several city agencies and transformed into spatial data that can be used for reference or analysis for measuring distance, drawing buffers, or counting features within areas. The data is provided in ESRI Geodatabase format."
  ],
  "dct_language_sm": ["eng"],
  "dct_creator_sm": ["GIS Lab, Newman Library, Baruch CUNY"],
  "dct_publisher_sm": ["Newman Library (Bernard M. Baruch College)"],
  "schema_provider_s": "Baruch CUNY",
  "gbl_resourceClass_sm": ["Datasets"],
  "gbl_resourceType_sm": ["Mixed data"],
  "dct_subject_sm": ["Boroughs", "Counties"],
  "dcat_theme_sm": ["Boundaries"],
  "dcat_keyword_sm": ["GBL Fixture records"],
  "dct_temporal_sm": ["2010, 2016"],
  "dct_issued_s": "2016-01-15",
  "gbl_indexYear_im": [2010],
  "gbl_dateRange_drsim": ["[2010 TO 2016]"],
  "dct_spatial_sm": [
    "New York, New York",
    "Bronx County, New York",
    "Kings County, New York",
    "New York County, New York",
    "Queens County, New York",
    "Richmond County, New York",
    "Borough of Bronx, New York",
    "Borough of Brooklyn, New York",
    "Borough of Manhattan, New York",
    "Borough of Queens, New York",
    "Borough of Staten Island, New York"
  ],
  "locn_geometry": "ENVELOPE(-74.255895,-73.700272,40.915282,40.495929)",
  "dcat_bbox": "ENVELOPE(-74.255895,-73.700272,40.915282,40.495929)",
  "dcat_centroid": "40.7056055,-73.9780835",
  "dct_accessRights_s": "Public",
  "dct_format_s": "Geodatabase",
  "gbl_wxsIdentifier_s": "sdr:nyu_2451_34636",
  "dct_references_s": "{\"http://lccn.loc.gov/sh85035852\":\"https://archive.nyu.edu/retrieve/74857/nyu_2451_34636_doc.zip\",\"http://schema.org/downloadUrl\":\"https://archive.nyu.edu/retrieve/74856/nyu_2451_34636.zip\",\"http://schema.org/url\":\"http://hdl.handle.net/2451/34636\"}",
  "id": "nyu_2451_34636",
  "dct_identifier_sm": ["http://hdl.handle.net/2451/34636"],
  "gbl_mdModified_dt": "2021-06-01T22:14:15Z",
  "gbl_mdVersion_s": "Aardvark"
}

=== geoblacklight/geoblacklight/spec/fixtures/solr_documents/no_spatial.json
{
  "dct_title_s": "ASTER Global Emissivity Dataset 1-kilometer V003 - AG1KM",
  "dct_alternative_sm": ["no_spatial"],
  "dct_description_sm": [
    "File without geometry type or locn_geometry (will cause error). ",
    "The Advanced Spaceborne Thermal Emission and Reflection radiometer Global Emissivity Database (ASTER GED) was developed by the National Aeronautics and Space Administration's (NASA) Jet Propulsion Laboratory (JPL), California Institute of Technology. The North America portion of this collection was formerly called the North American ASTER Land Surface Emissivity Database (NAALSED) - a seasonal dataset consisting of mean summer (J-A-S) and winter (J-F-M) products. ASTER GED products are output on 1degree x 1 degree grids at 100-meter or 1-kilometer spatial resolution (nominal) and include the mean emissivity and standard deviation for all 5 ASTER thermal infrared bands, mean land surface temperature (LST) and standard deviation, a re-sampled ASTER GDEM (not included in the North America Winter products), land-water mask, mean Normalized Difference Vegetation Index (NDVI) and standard deviation, latitude, longitude, and observation count. Additional ASTER GED product information is available at https://lpdaac.usgs.gov/products/community_products_table. Product tiles are available in HDF and binary format and may be downloaded via HTTP by visiting the following data clients: NASA Reverb (http://reverb.echo.nasa.gov), LP DAAC Data Pool (http://e4ftl01.cr.usgs.gov/ASTT/), or EarthExplorer (http://earthexplorer.usgs.gov)."
  ],
  "schema_provider_s": "U.S. Geological Survey, Department of the Interior",
  "gbl_resourceClass_sm": ["Imagery"],
  "dct_subject_sm": [
    "Land surface temperature",
    "U.S. Geological survey (USGS)",
    "Earth observing system",
    "Land processes distributed active archive center (LPDAAC)",
    "Aster",
    "Normalized difference vegetation index",
    "Terra",
    "Image map",
    "Emissivity"
  ],
  "dcat_keyword_sm": ["GBL Fixture records"],
  "dct_accessRights_s": "Public",
  "dct_references_s": "{}",
  "id": "aster-global-emissivity-dataset-1-kilometer-v003-ag1kmcad20",
  "dct_identifier_sm": ["c0515c4e-97dc-4fff-82cb-f65144482631"],
  "gbl_mdModified_dt": "2021-06-01T22:14:16Z",
  "gbl_mdVersion_s": "Aardvark"
}

=== geoblacklight/geoblacklight/spec/fixtures/solr_documents/esri-wms-layer.json
{
  "dct_title_s": "Bedrock Geology: Illinois, 2005",
  "dct_alternative_sm": ["esri-wms-layer"],
  "dct_description_sm": [
    "Dataset with ArcGIS Dynamic Map Layer, ArcGIS WMS, and direct download. ",
    "This feature dataset shows the distribution and extent of the bedrock geologic units within the State of Illinois, as depicted on the map Bedrock Geology of Illinois (2005) by D. Kolata (compiler), published by the Illinois State Geological Survey. The component feature classes show geologic units (polygons) and faults (lines). The nominal scale of the published hardcopy map is 1:500,000."
  ],
  "dct_language_sm": ["eng"],
  "dct_creator_sm": ["Illinois State Geological Survey"],
  "dct_publisher_sm": ["Illinois State Geological Survey"],
  "schema_provider_s": "University of Illinois Urbana-Champaign",
  "gbl_resourceClass_sm": ["Datasets", "Web services"],
  "gbl_resourceType_sm": ["Polygon data"],
  "dct_subject_sm": ["Geology"],
  "dcat_theme_sm": ["Geology"],
  "dcat_keyword_sm": ["GBL Fixture records"],
  "dct_temporal_sm": ["2005"],
  "dct_issued_s": "2005",
  "gbl_indexYear_im": [2005],
  "gbl_dateRange_drsim": ["[2005 TO 2005]"],
  "dct_spatial_sm": ["Illinois"],
  "locn_geometry": "ENVELOPE(-91.5826823,-87.38401652,42.49563968,36.95351896)",
  "dcat_bbox": "ENVELOPE(-91.5826823,-87.38401652,42.49563968,36.95351896)",
  "dcat_centroid": "39.72457932,-89.48334941",
  "dct_accessRights_s": "Public",
  "dct_format_s": "Shapefile",
  "gbl_wxsIdentifier_s": "0",
  "dct_references_s": "{\"http://schema.org/downloadUrl\":\"https://clearinghouse.isgs.illinois.edu/sites/clearinghouse.isgs/files/Clearinghouse/data/ISGS/Geology/zips/IL_Bedrock_Geology_500K_2005_Py.zip\",\"http://schema.org/url\":\"https://clearinghouse.isgs.illinois.edu/data/geology/bedrock-geology-2005\",\"http://www.opengis.net/cat/csw/csdgm\":\"https://clearinghouse.isgs.illinois.edu/sites/clearinghouse.isgs/files/clearinghouse/data/metadata/ISGS/IL_Bedrock_Geology_500K_2005_Py.xml\",\"http://www.w3.org/1999/xhtml\":\"https://clearinghouse.isgs.illinois.edu/sites/clearinghouse.isgs/files/clearinghouse/data/metadata/ISGS/IL_Bedrock_Geology_500K_2005_Py.html\",\"urn:x-esri:serviceType:ArcGIS#DynamicMapLayer\":\"https://data.isgs.illinois.edu/arcgis/rest/services/Geology/Bedrock_Geology_500K_2005/MapServer\",\"http://www.opengis.net/def/serviceType/ogc/wms\":\"https://data.isgs.illinois.edu/arcgis/services/Geology/Bedrock_Geology_500K_2005/MapServer/WMSServer\"}",
  "id": "5f92e192-7e3f-4ec7-a193-8c165288560a",
  "dct_identifier_sm": ["5f92e192-7e3f-4ec7-a193-8c165288560a"],
  "gbl_mdModified_dt": "2026-08-29T00:00:00Z",
  "gbl_mdVersion_s": "Aardvark"
}

=== geoblacklight/geoblacklight/spec/fixtures/solr_documents/public_iiif_princeton.json
{
  "dct_title_s": "The provinces of New York and New Jersey, with part of Pensilvania, and the Province of Quebec : drawn by Major Holland, Surveyor General, of the Northern District in America. Corrected and improved, from the original materials, by Governr. Pownall, Member of Parliament, 1776",
  "dct_alternative_sm": ["public_iiif_princeton"],
  "dct_description_sm": [
    "Scanned map with IIIF. ",
    "Partly colored. Relief shown pictorially. Shows administrative divisions. From Thomas Jefferys's The American atlas, or, A geographical description of the whole continent of America (London : Printed by R. Sayer and Bennett, 1778). Insets: A chart of the mouth of Hudson's River, from Sandy Hook to New York. A plan of the city of New York. Plan of Amboy, with its environs, from an actual survey."
  ],
  "dct_language_sm": ["eng"],
  "dct_creator_sm": ["Rogers, Henry Darwin", "Pownall, Thomas"],
  "dct_publisher_sm": ["London, Robt. Sayer & John Bennett"],
  "schema_provider_s": "Princeton",
  "gbl_resourceClass_sm": ["Maps"],
  "gbl_resourceType_sm": ["Raster data"],
  "dct_subject_sm": ["New York (State)‒Maps", "New Jersey‒Maps"],
  "dcat_keyword_sm": ["GBL Fixture records"],
  "dct_temporal_sm": ["1778"],
  "dct_issued_s": "1904-11-12",
  "gbl_indexYear_im": [1778],
  "gbl_dateRange_drsim": ["[1778 TO 1778]"],
  "dct_spatial_sm": ["New York (State)", "New Jersey", "Pennsylvania"],
  "locn_geometry": "ENVELOPE(-76.3394,-72.1916,46.5798,38.6693)",
  "dcat_bbox": "ENVELOPE(-76.3394,-72.1916,46.5798,38.6693)",
  "dcat_centroid": "42.62455,-74.2655",
  "dct_accessRights_s": "Public",
  "dct_format_s": "Raster",
  "gbl_wxsIdentifier_s": "02870w62c",
  "dct_references_s": "{\"http://iiif.io/api/image\":\"https://iiif-cloud.princeton.edu/iiif/2/6c%2F52%2F12%2F6c5212e81bc845f59bb1cdc740a88bad%2Fintermediate_file/info.json\",\"http://schema.org/url\":\"http://arks.princeton.edu/ark:/88435/02870w62c\"}",
  "id": "princeton-02870w62c",
  "dct_identifier_sm": ["http://arks.princeton.edu/ark:/88435/02870w62c"],
  "gbl_mdModified_dt": "2021-06-01T22:14:16Z",
  "gbl_mdVersion_s": "Aardvark"
}

=== geoblacklight/geoblacklight/spec/fixtures/solr_documents/esri-tiled_map_layer.json
{
  "dct_title_s": "Minnesota Land Cover Classification and Impervious Surface Area by Landsat and Lidar (2013 Update)",
  "dct_description_sm": [
    "This is a 15-meter raster dataset of a land cover and impervious surface classification for 2013, level two classification. The classification was created using a combination of multitemporal Landsat 8 data and LiDAR data with Object-based image analysis. By using objects instead of pixels we were able to utilize multispectral data along with spatial and contextual information of objects such as shape, size, texture and LiDAR-derived metrics to distinguish different land cover types. While OBIA has become the standard procedure for classification of high resolution imagery we found that it works equally well with Landsat imagery. For the objects classified as urban or developed, a regression model relating the Landsat greenness variable to percent impervious was developed to estimate and map the percent impervious surface area at the pixel level."
  ],
  "dct_language_sm": ["eng"],
  "dct_creator_sm": ["Bauer, Marvin E.", "Knight, Joe F.", "Rampi, Lian P."],
  "schema_provider_s": "University of Minnesota",
  "gbl_resourceClass_sm": ["Datasets"],
  "gbl_resourceType_sm": ["Vector data", "Raster data", "LiDAR"],
  "dcat_theme_sm": ["Imagery"],
  "dcat_keyword_sm": ["Lidar", "Landsat Satellites", "Land cover", "2022-creator-sprint"],
  "dct_temporal_sm": ["2013"],
  "dct_issued_s": "2016-08-03",
  "gbl_indexYear_im": [2013],
  "gbl_dateRange_drsim": ["[2013 TO 2013]"],
  "dct_spatial_sm": ["Minnesota"],
  "locn_geometry": "POLYGON((-97.23 49.37, -89.53 49.37, -89.53 43.5, -97.23 43.5, -97.23 49.37))",
  "dcat_bbox": "ENVELOPE(-97.23,-89.53,49.37,43.5)",
  "dcat_centroid": "46.435,-93.38",
  "pcdm_memberOf_sm": ["dc8c18df-7d64-4ff4-a754-d18d0891187d"],
  "dct_isPartOf_sm": ["05d-03"],
  "dct_rights_sm": ["https://conservancy.umn.edu/pages/drum/policies/#terms-of-use"],
  "dct_license_sm": ["http://creativecommons.org/publicdomain/zero/1.0/"],
  "dct_accessRights_s": "Public",
  "dct_format_s": "GeoTIFF",
  "dct_references_s": "{\"http://lccn.loc.gov/sh85035852\":\"https://conservancy.umn.edu/bitstream/handle/11299/181555/Classification%20scheme%20for%20Level%201%20and%202%20land%20cover%20classes%202013.pdf\",\"http://schema.org/downloadUrl\":[{\"label\":\"Original GeoTIFF\",\"url\":\"https://conservancy.umn.edu/bitstream/handle/11299/181555/Statewide_FinalMap_2013_2014_v2.zip\"}],\"http://www.opengis.net/cat/csw/csdgm\":\"https://conservancy.umn.edu/bitstream/handle/11299/181555/Statewide_LandCoverMetadata_MN_2013_v2.xml\",\"http://www.w3.org/1999/xhtml\":\"https://conservancy.umn.edu/bitstream/handle/11299/181555/Statewide_LandCover_Metadata_MN_2013_v2.html\",\"http://schema.org/url\":\"http://doi.org/10.13020/D6JP4S\",\"urn:x-esri:serviceType:ArcGIS#TiledMapLayer\":\"https://tiles.arcgis.com/tiles/8df8p0NlLFEShl0r/arcgis/rest/services/mn_landcover_impervious_2013v2_tiles/MapServer\"}",
  "id": "31567cf1-bad8-4bc5-8d57-44b96c207ecc",
  "dct_identifier_sm": ["http://doi.org/10.13020/D6JP4S", "http://hdl.handle.net/11299/181555"],
  "gbl_mdVersion_s": "Aardvark"
}

=== geoblacklight/geoblacklight/spec/fixtures/solr_documents/wmts-single-layer.json
{
  "gbl_mdVersion_s": "Aardvark",
  "dct_identifier_sm": ["ark:/99999/fk4544658v"],
  "id": "princeton-fk4544658v-wmts",
  "dct_title_s": "The Balkans [and] Turkey : G.S.G.S. no. 2097 / War Office. General Staff. Geographical Section (WMTS Fixture)",
  "locn_geometry": "ENVELOPE(19.333333, 29.333333, 43.083333, 39.75)",
  "dcat_bbox": "ENVELOPE(19.333333, 29.333333, 43.083333, 39.75)",
  "schema_provider_s": "Princeton",
  "dct_accessRights_s": "Public",
  "dct_description_sm": [
    "Relief shown by contours approximately 100 feet interval, spot heights, and shading. Title varies; some sheets are titled \"Turkey\". Shows international boundaries, railways, 2 categories of roads, telegraph lines, places of worship, ruins. Constantinople latest edition map has a glossary."
  ],
  "dct_creator_sm": ["Great Britain. War Office. General Staff. Geographical Section"],
  "dct_language_sm": ["eng"],
  "dct_publisher_sm": ["[London] : War Office. General Staff. Geographical Section. General Staff, 1908-25."],
  "dct_subject_sm": ["Balkan Peninsula Maps", "Turkey Maps", "Topographic Maps"],
  "dct_spatial_sm": ["Balkan Peninsula", "Turkey"],
  "dct_issued_s": "1908",
  "gbl_indexYear_im": [1908],
  "gbl_mdModified_dt": "2022-02-03T22:13:40Z",
  "gbl_wxsIdentifier_s": "mosaic",
  "dct_references_s": "{\"http://schema.org/url\":\"https://catalog.princeton.edu/catalog/99125413918506421\",\"http://schema.org/thumbnailUrl\":\"https://figgy-staging.princeton.edu/downloads/6b55d939-7188-4bce-9550-0ac535441f22/file/9042b887-da2e-4aa9-9ca5-d3ba77f440c4\",\"http://iiif.io/api/image\":\"https://iiif-cloud-staging.princeton.edu/iiif/2/05%2F71%2F04%2F0571046f9c7149a3b950899323f70788%2Fintermediate_file/info.json\",\"http://iiif.io/api/presentation#manifest\":\"https://figgy-staging.princeton.edu/concern/scanned_maps/2a91d82c-541c-426c-b787-cc62afe8f248/manifest\",\"http://www.opengis.net/def/serviceType/ogc/wmts\":\"https://map-tiles-staging.princeton.edu/2a91d82c541c426cb787cc62afe8f248/mosaicjson/WMTSCapabilities.xml\"}",
  "gbl_resourceClass_sm": ["Maps", "Web services"],
  "gbl_resourceType_sm": ["Military maps", "Topographic maps"]
}

=== geoblacklight/geoblacklight/spec/fixtures/solr_documents/actual-papermap1.json
{
  "dct_title_s": "1:1 500 000 series [cartographic material] : tectonic map of Britain, Ireland and adjacent areas / British Geological Survey ; Geological Survey of Ireland ; Geological Survey of Northern Ireland.",
  "dct_alternative_sm": ["actual-papermap1"],
  "dct_description_sm": [
    "Nondigitized paper map with a link to a library catalog. ",
    "Panel title. Depths shown by isolines. \"Geological map [copyright] NERC 1996.\" Also available on flat sheet. \"Sheet 1\"--on panel. Includes text, notes, organizations\\' logos, and ancillary map of \"Orogenic terranes of Britain, Ireland and surrounding seas.\""
  ],
  "dct_language_sm": ["eng"],
  "dct_publisher_sm": ["British Geological Survey"],
  "schema_provider_s": "MIT",
  "gbl_resourceClass_sm": ["Maps"],
  "dcat_keyword_sm": ["Paper map", "GBL Fixture records"],
  "dct_temporal_sm": ["1996"],
  "dct_issued_s": "1905-06-22",
  "gbl_indexYear_im": [1996],
  "gbl_dateRange_drsim": ["[1996 TO 1996]"],
  "locn_geometry": "ENVELOPE(-13,4,62,49)",
  "dcat_bbox": "ENVELOPE(-13,4,62,49)",
  "dcat_centroid": "55.5,-4.5",
  "dct_accessRights_s": "Public",
  "dct_format_s": "Paper",
  "gbl_wxsIdentifier_s": "MIT:001145244",
  "dct_references_s": "{\"http://schema.org/url\":\"http://library.mit.edu/item/001145244\"}",
  "id": "mit-001145244",
  "dct_identifier_sm": ["urn:arrowsmith.mit.edu:MIT.001145244"],
  "gbl_mdModified_dt": "2021-06-11T18:30:23Z",
  "gbl_mdVersion_s": "Aardvark"
}
